### ISSUE TITLE
Follow and unfollow

### ISSUE THREAD

**Issue by mandriv** [lejhy/Miotag#10]
Hi Filip, I am having some troubles with following and unfollowing users, I sometimes get 400
```
Required request body is missing: public boolean Miotag.controller.RelationController.unfollow(Miotag.dto.UserDto,Miotag.model.User)
```
Would it be much of a problem for you to change the methods so they don't require body in the requests like so:
POST `/follow/:userId` or even better `/users/:id/follow`
and
DELETE `/follow/:userId` or `/users/:id/follow`

Just asking.

**Comment by lejhy** [comment]
It's easy to implement, but I feel it would be too confusing to have a state-changing variable in the path... 
But on the other hand, I see what you mean, I'll change it to:
POST `/relations/:userId`
and
DELETE `/relations/:userId`

Don't wanna change "relations" to "follow", since the name is already established, but up for debate...

**Comment by mandriv** [comment]
This is not a priority atm, just wanted to point it out that would help.
Meanwhile, could you help me debug this error message? It shows up only when trying to unfollow.

**Comment by mandriv** [comment]
And relations endpoint is fine.

**Comment by lejhy** [comment]
The reason for the error is probably that you're not including the body in the request, which should be the User object with an id set (other fields can be null), something like:
{
 id: <id>
}

**Comment by lejhy** [comment]
Anyway, issue resolved and new code tested, so no need to worry about the error anymore ;)
